Feature: Tabs Component 추가
shopl/shoplflow pull request #255
Opened 2024-02-01 06:56 UTC by velo-kim

## 🔨작업 내용

Tabs Component 추가

## 머지 전 확인해주세요.

> shoplflow는 [트렁크 기반 전략](https://www.notion.so/shoplworks/Gitflow-19b201245a6d4d129731ec2136c62a8e?pvs=4)을 사용하고 있습니다.
>
> 머지 전에 아래 항목들을 확인해주세요.

- [ ] 추가되는 기능에 대한 테스트 코드가 작성되었나요?
- [ ] 해당 업데이트로 인해 기존에 작성된 테스트 코드가 실패하지 않나요?
- [ ] 머지 전에 빌드가 성공했나요?
- [ ] 린트가 적용되어 있나요?

2024-02-01 07:23 UTC, Jason-Jeong-Dev commented
**논의했던 것들 정리드립니다.**
- Tab은 단일 버튼을 의미한다.
- 기존에 개발하신 로직은 별도로 네이밍 처리

**Tab 단일 요소 변경되어야할 점**
- level 단위 구분이 아닌 형태로 구분하기 (styleVar, sizeVar)
  - level1, level2 는 sizeVar로 분리
  - level3는 styleVar로 분리

**디자이너 분들과 협의해야할 점**
- level3 바덤 애니메이션 관련 논의
  - 하단부터 늘어나는 애니메이션이 맞는건지 확인
  - 바텀 바가 선택된 Tab에 슬라이드되는 애니메이션은 어떤지?
 - 선택된 Tab의 컬러가 변경되어야할 경우가 있는지

2024-02-01 07:33 UTC, Jason-Jeong-Dev commented
저는 이런 형태를 떠올렸는데 이름은 무시하고 형태만 봐주세요~
```
<Tab>
    <Tab.Item />
    <Tab.Item />
    <Tab.Item />
</Tab>
<SwitchCase
  value={status}
  caseBy={{
    a: <TypeA />,
    b: <TypeB />,
    c: <TypeC />,
  }}
  initialValue={'a'}
/>
```

2024-02-01 07:42 UTC, Jason-Jeong-Dev requested changes

2024-02-01 07:42 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Tabs/Tabs.types.ts
> +  onChangeTab?: (tab: string) => void;
onChange로도 충분히 그 역할을 알 수 있을 것 같아요~

2024-03-26 23:20 UTC, velo-kim commented on packages/base/src/components/Tabs/Tabs.types.ts
> +  onChangeTab?: (tab: string) => void;
수정 완료~!

2024-03-26 23:21 UTC, closed without merging