feat: Title 컴포넌트 생성
shopl/shoplflow pull request #382
Opened 2024-09-05 06:16 UTC by ayaan0209

## 🔨작업 내용

- Title 컴포넌트 만들었습니다.

## 📸 스크린샷(선택)

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

## 머지 전 확인해주세요.

> shoplflow는 [트렁크 기반 전략](https://www.notion.so/shoplworks/Gitflow-19b201245a6d4d129731ec2136c62a8e?pvs=4)을 사용하고 있습니다.
>
> 머지 전에 아래 항목들을 확인해주세요.

- [ ] 추가되는 기능에 대한 테스트 코드가 작성되었나요?
- [ ] 해당 업데이트로 인해 기존에 작성된 테스트 코드가 실패하지 않나요?
- [ ] 머지 전에 빌드가 성공했나요?
- [ ] 린트가 적용되어 있나요?

2024-09-05 06:40 UTC, velo-kim commented on packages/base/src/components/Title/Title.tsx
> +          {showHelpIcon && (
피그마 디자인에 required와 help 중간에 숫자가 들어가는 케이스도 있는데 대응이 어려워보입니다!

2024-09-05 06:40 UTC, velo-kim commented on packages/base/src/components/Title/Title.tsx
> +          <Text typography={'body1_400'} color={'neutral500'}>
하다의 Title 디스크립션 Text typography는 body2_400인거 같아요! body1_400의 Text로 고정되는 것 보다, rightSource처럼 받는것도 괜찮을 거 같아요!

2024-09-05 06:40 UTC, velo-kim commented on packages/base/src/components/Title/Title.types.ts
> +export interface TitleProps extends RightElementProps {
개인적인 선호도인데, 저는 interface보다 type을 선언해요! TitleProps는 뭔가 인터페이스 병합에 위험성이 있어보입니다ㅠ

2024-09-05 06:40 UTC, velo-kim commented on packages/base/src/components/Title/Title.mdx
깔끔하게 정리되었네요! 수고하셨씁니당

2024-09-09 00:15 UTC, dev-bomdong commented on packages/base/src/components/Title/Title.tsx
> +            {title} {isRequired && <Styled.Required>*</Styled.Required>}
필수 표시(*)는 `<Text color={'red300'}>*</Text>`로 대체할 수 있을 것 같아요. 그럼 Title.styled.ts 파일도 삭제할 수 있을 듯 합니다!

2024-09-09 00:19 UTC, dev-bomdong commented on packages/base/src/components/Title/Title.types.ts
> +  showTooltip?: boolean;
boolean값에 대한 Prop은 isRequired처럼 `is~` 로 통일해서 사용하는 건 어떨까요?

2024-09-09 00:23 UTC, dev-bomdong commented on packages/base/src/components/Title/Title.tsx
> +          <Text color={titleColor} typography={titleTypography} style={{ wordWrap: 'break-word' }}>
인라인 스타일링으로 되어있는 wordWrap속성을 `<Text wordBreak='break-all'/>`으로 대체할 수 있어보여요!

2024-09-09 00:29 UTC, dev-bomdong commented on packages/base/src/components/Title/Title.tsx
> +          </Text>
설명 영역엔 줄바꿈 처리가 안되어있는 것 같은데, 타이틀 영역처럼 줄바꿈 처리가 필요할 것 같습니다!

2024-09-09 00:29 UTC, dev-bomdong requested changes
궁금한 점들이나 제안하는 부분들 코멘트 남겨두었습니다 ~ 고생하셨습니다!! 🙇‍♀️

2024-09-09 03:42 UTC, ayaan0209 commented on packages/base/src/components/Title/Title.types.ts
> +  showTooltip?: boolean;
그렇게 하는게 좀 더 통일감있고 좋아보이네요. 해당 사항 반영해놓겠습니다!

2024-09-09 04:21 UTC, dev-bomdong approved these changes

2024-09-09 04:23 UTC, merged