feature: icons
shopl/shoplflow pull request #41
Opened 2023-08-17 06:37 UTC by velo-kim

## 🔨작업 내용

- shopl-assets, hada-assets packages 작업
- {build,lint}:{icons,illustrations} scripts

## 📸 스크린샷(선택)

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

- shopl-assets, hada-assets 내부의 파일이 겹치는 사항이 많은데, 좀 더 깔끔하게 정리할 방법이 있다면 공유 해주세요!

## 머지 전 확인해주세요.

> shoplflow는 [트렁크 기반 전략](https://www.notion.so/shoplworks/Gitflow-19b201245a6d4d129731ec2136c62a8e?pvs=4)을 사용하고 있습니다.
>
> 머지 전에 아래 항목들을 확인해주세요.

- [ ] 추가되는 기능에 대한 테스트 코드가 작성되었나요?
- [ ] 해당 업데이트로 인해 기존에 작성된 테스트 코드가 실패하지 않나요?
- [ ] 머지 전에 빌드가 성공했나요?
- [ ] 린트가 적용되어 있나요?

2023-08-17 07:06 UTC, Jason-Jeong-Dev requested changes

2023-08-17 07:06 UTC, Jason-Jeong-Dev commented on packages/hada-assets/CHANGELOG.md
배포하면 자동으로 생성될거라 이건 삭제해주셔도 될 것 같아요.

2023-08-17 07:09 UTC, velo-kim commented on packages/hada-assets/CHANGELOG.md
넵~ 삭제할게요!

2023-08-18 00:02 UTC, Jason-Jeong-Dev approved these changes
굿 수고하셨습니다

2023-08-18 00:03 UTC, merged