feat: add Minus Button and Toggle Switch
shopl/shoplflow pull request #69
Opened 2023-09-14 05:17 UTC by dev-bomdong

## 🔨작업 내용

[SHP-14594](https://shoplworks.atlassian.net/browse/SHP-14594) Minus Button 개발
[SHP-14621](https://shoplworks.atlassian.net/browse/SHP-14621) Toggle Switch 개발

## 📸 스크린샷(선택)

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들

## 머지 전 확인해주세요.

> shoplflow는 [트렁크 기반 전략](https://www.notion.so/shoplworks/Gitflow-19b201245a6d4d129731ec2136c62a8e?pvs=4)을 사용하고 있습니다.
>
> 머지 전에 아래 항목들을 확인해주세요.

- [ ] 추가되는 기능에 대한 테스트 코드가 작성되었나요?
- [x] 해당 업데이트로 인해 기존에 작성된 테스트 코드가 실패하지 않나요?
- [x] 머지 전에 빌드가 성공했나요?
- [x] 린트가 적용되어 있나요?

2023-09-14 05:50 UTC, Jason-Jeong-Dev requested changes
수고하셨습니다! 코멘트 확인부탁드려요

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/MinusBox/MinusBox.mdx
> +        <MinusButton onChange={() => { console.log('예시입니다') }}/>
onChange가 아닌 onClick 아닌가요?!

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/MinusBox/MinusBox.mdx
> +        <MinusButton color={'shopl300'} hoverColor={'shopl400'} onChange={() => { console.log('예시입니다') }}/>
요기도 동일합니다!

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/MinusBox/MinusBox.styled.ts
> +  border-radius: ${borderRadiusTokens['borderRadius04']};
var(--borderRadius04);로 교체해주세요!

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/MinusBox/MinusBox.types.ts
> +   * hover 상태의 요소 ㄴ배경색
오타있습니다!

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +    background: ${({ isDisabled }) => !isDisabled && 'rgba(51, 51, 51, 0.05)'};
컬러토큰으로 교체가 필요해보여요.!
진과 상의해야할 것 같네용

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.tsx
> +          setActive((prev) => !prev);
disable이 true일 때 상태 변경이 안되면 좋을 것 같습니다

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.tsx
> +  activeColor = 'shopl300',
메인 컬러(도메인 관련 primary컬러)를 사용하는 경우 primary로 작성해주세요!
shopl300 -> primary300
hada200 -> primary200

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.tsx
> +          setActive((prev) => !prev);
이전에 경험했던 이슈인데 `setActive((prev) => !prev);`로 상태변경시 외부 상태와 스위치 컴포넌트 내부의 상태의 sync가 맞지 않는 이슈가 있었습니다
클릭해서 내부 상태를 변경하는 것도 가능하지만 외부에서 할당된 상태가 우선시 되도록 변경해주세요

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.mdx
> +```
하단에 ArgsTable도 추가해주세요!

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +  // inActive
active와 unactive 스타일이 같이 있는데 분리가 가능할 것 같아요.
공통된 스타일을 제외하고 분기처리하면 좋을 것 같아요

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +  background: ${colorTokens['neutral350']};
var(--neutral350)으로 교체해주세요!

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +      background: ${colorTokens['neutral0']};
var(--neutral0)으로 교체해주세요!

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.mdx
이전에도 진과 얘기했던 내용인데요. 
네이밍 관한건데 Toggle과 Switch 비슷한 의미를 가지고 있는 것 같아 Toggle로 통일하자고 했던 기억이 있어요.
이건 한번 얘기 나눠보시면 좋을 것 같네용

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.mdx
다른 버튼들은 "선택됨"에 대한 옵션이 selected인데 toggle은 active인 점이 좀 의문입니다.
다른 컴포넌트와의 조합을 위해서 selected로 통일하면 좋을 것 같아요

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.mdx
> +import { ToggleSwitchProps } from "@shoplflow/base"; import ToggleSwitch from "./ToggleSwitch";
줄바꿈해주세요!

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/MinusBox/MinusBox.types.ts
> +  hoverColor?: ColorTokens;
color와 hover 컬러가 있는데 두가지 선택지를 주는 것도 좋지만 규칙으로 통일해서 개발자의 공수를 줄이면 좋겠다는 생각이 들어요. 한번 고려해주세요!

ex)hover 컬러는 기본컬러를 기준으로 2단계 윗 컬러를 사용한다

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +    background: ${colorTokens['neutral0']};
var(--neutral0)으로 교체해주세요!

2023-09-14 05:50 UTC, Jason-Jeong-Dev commented on .changeset/wise-birds-rest.md
> +"@shoplflow/base": major
메이저 버전도 올라가있는데 해당 파일은 삭제해주세요!

2023-09-14 05:54 UTC, Jason-Jeong-Dev commented
추가적으로 스토리북 확인해봤는데 토클 버튼> Default 에서 isActive control시 동작하지 않습니다 확인부탁드려요!

https://shoplflow-base-git-feature-control-buttons-shoplworks.vercel.app/?path=/story/components-toggleswitch--default&args=activeColor:neutral700;isActive:!false

2023-09-14 05:59 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.mdx
`utils/type/ComponentProps.ts` 파일에 SelectedProps이라는 타입을 선언해두고 여러 컴포넌트에서 사용하는 것도 좋은 방법 같아요

2023-09-14 06:04 UTC, dev-bomdong commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.mdx
> 다른 버튼들은 "선택됨"에 대한 옵션이 selected인데 toggle은 active인 점이 좀 의문입니다. 다른 컴포넌트와의 조합을 위해서 selected로 통일하면 좋을 것 같아요

디자인 가이드와 네이밍을 통일하기 위해 active로 표기했습니다.
이건 jin과 상의해볼게요!

2023-09-14 06:43 UTC, Jason-Jeong-Dev commented on packages/base/src/components/MinusBox/MinusBox.styled.ts
> +  border-radius: ${borderRadiusTokens['borderRadius04']};
죄송합니다 CSS 토큰을 사용하는게 아니라 `borderRadiusTokens.borderRadius04` 이렇게 부탁드릴게요!

2023-09-14 06:43 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +    background: ${colorTokens['neutral0']};
죄송해요.`colorTokens. neutral0`로 부탁드립니다!!

2023-09-14 06:44 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +  background: ${colorTokens['neutral350']};
죄송합니다.. `colorTokens.neutral350`로 부탁드려요

2023-09-14 06:45 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +      background: ${colorTokens['neutral0']};
`colorTokens.neutral0`로 부탁드려요..!!

2023-09-14 06:45 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.mdx
넵넵 피그마에도 동일하게 나와있어서 진과 상의해주시면 될 것 같아요 감사합니다!

2023-09-15 06:28 UTC, velo-kim approved these changes

2023-09-15 06:28 UTC, velo-kim commented on packages/base/src/components/MinusBox/MinusBox.tsx
> +  ({ onClick, color = 'neutral300', hoverColor = 'neutral400', ...rest }: MinusBoxProps, ref) => {
이렇게 forwardRef 제네릭을 직접 주입하니까 좀 더 컴포넌트 분석이 쉬운거 같아서  좋은 듯해요!
제네릭 영역 말고, 함수 첫번째 파라미터 부분 MinusBoxProps 타입 명시해줘야 되는 이유가 있을까요?

2023-09-20 06:09 UTC, dev-bomdong commented on .changeset/wise-birds-rest.md
> +"@shoplflow/base": major
해당 파일은 changeset 설정을 하며 자동생성되었는데 생성되지 말아야할 파일일까요? 만약 그렇다면 추후에도 PR 올리기 전 한 번씩 확인해보려구요

2023-09-20 06:15 UTC, dev-bomdong commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.tsx
> +          setActive((prev) => !prev);
disabled이 true일 땐 onchange가 실행되지 않는데 onchange 내부에 방어로직을 넣어야 할 필요가 있을까요?

2023-09-20 06:21 UTC, dev-bomdong commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.tsx
> +          setActive((prev) => !prev);
disabled 상태일 땐 onChange가 실행되지 않아 상태 변경이 되지 않는데, 어떤 부분을 말씀하시는걸까요??

2023-09-20 06:25 UTC, dev-bomdong commented on packages/base/src/components/MinusBox/MinusBox.tsx
> +  ({ onClick, color = 'neutral300', hoverColor = 'neutral400', ...rest }: MinusBoxProps, ref) => {
prop에 대한 타입을 더 명시적으로 알려주기 위함이였는데, 코멘트 확인 후 다시 코드를 보니 굳이 두 번 작성된 느낌이네요. 제네릭으로도 충분히 명시 가능한 듯 싶어 함수 파라미터 부분의 타입 명시부분은 삭제해두었습니다!

2023-09-20 06:48 UTC, dev-bomdong commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.mdx
jin과 toggle로 합의했습니다! 컴포넌트 명칭같은건 개발팀쪽에서 적극적으로 의견내는 게 더 좋다고 하시네요

2023-09-20 08:02 UTC, dev-bomdong commented on packages/base/src/components/MinusBox/MinusBox.mdx
> +        <MinusButton onChange={() => { console.log('예시입니다') }}/>
minus button은 단순 버튼이 아닌 checkbox의 역할을 하는 용도로 만들어졌기에 (table row에 사용) `<input type="checkbox"/>`로 만들었는데요, input에선 onclick보다 onchange를 사용하도록 [공식문서](https://react.dev/reference/react-dom/components/input#my-checkbox-doesnt-update-when-i-click-on-it)에서 권장하고 있고,  웹 접근성 측면에서도 더 적절하기에 (onclick은 mouse click으로만 동작) onchange를 사용했습니다.

2023-09-21 02:26 UTC, Jason-Jeong-Dev commented on .changeset/wise-birds-rest.md
> +"@shoplflow/base": major
changeset를 실행하면 major 업데이트인지 minor 업데이트인지 선택지를 주는데 해당 업데이트를 선택하셨는지 한번 체크 부탁드립니당

2023-09-21 02:29 UTC, Jason-Jeong-Dev commented on packages/base/src/components/MinusBox/MinusBox.mdx
> +        <MinusButton onChange={() => { console.log('예시입니다') }}/>
아하 그렇군요 처음알았네요 답변감사합니다

2023-09-21 02:30 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.tsx
> +          setActive((prev) => !prev);
지금 보니..잘 동작하네요.. 죄송합니다

2023-09-21 04:01 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.mdx
넵 감사합니다 좋아요!

2023-09-27 02:22 UTC, dev-bomdong commented on packages/base/src/components/MinusBox/MinusBox.mdx
> +        <MinusButton onChange={() => { console.log('예시입니다') }}/>
논의가 무색하게.. 😇 본 컴포넌트는 클릭시 바로 동작되는 버튼 형태로 추가 협의되어 button 요소로 변경할 예정입니다! 태그가 바뀌었으니 onChange 함수도 onClick 함수로 변경하려 합니다.

2023-09-27 07:33 UTC, dev-bomdong commented on packages/base/src/components/MinusBox/MinusBox.mdx
> +        <MinusButton color={'shopl300'} hoverColor={'shopl400'} onChange={() => { console.log('예시입니다') }}/>
변경완료!

2023-09-27 07:34 UTC, dev-bomdong commented on packages/base/src/components/MinusBox/MinusBox.types.ts
> +  hoverColor?: ColorTokens;
jin과 background color 기준 한 단계 위 token을 사용하기로 협의해 반영해두었습니다.

2023-10-04 09:16 UTC, dev-bomdong commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +  // inActive
active, unactive 상태의 겹치는 스타일링 속성을 정리해두었습니다. Toggle 컴포넌트는 default, checked, disabled 상태에 따라 분기처리 됩니다.

2023-10-04 09:18 UTC, dev-bomdong commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.tsx
> +          setActive((prev) => !prev);
이 부분은 useOnToggle hook을 적용해두었습니다.

2023-10-09 23:16 UTC, Jason-Jeong-Dev commented on packages/base/src/components/MinusBox/MinusBox.mdx
> +        <MinusButton onChange={() => { console.log('예시입니다') }}/>
헐 그렇군요.. 넵넵 감사합니다 :)

2023-10-09 23:16 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.styled.ts
> +  // inActive
넵 감사합니다

2023-10-09 23:26 UTC, Jason-Jeong-Dev approved these changes
추가적으로 두 곳에 변경 요청드렸습니다!
각 컴포넌트의 조합에 용이하기 위해 적용되어야할 사항이니 같이 확인부탁드려요!

2023-10-09 23:26 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.types.ts
> +  isActive?: boolean;
ComponentProps.ts에 있는 SelectedProps로 교체할 수 있을까요?
온오프 관련 상태는 isSelected Props로 통일하려고 합니다!

2023-10-09 23:26 UTC, Jason-Jeong-Dev commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.types.ts
> +  isDisabled?: boolean;
위와 동일한데 ComponentProps.ts의 DisableProps로 교체 가능할까요??
공통으로 사용할만한 props는 통일하려고 해요!

2023-10-10 06:29 UTC, dev-bomdong commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.types.ts
> +  isActive?: boolean;
변경완료!

2023-10-10 06:29 UTC, dev-bomdong commented on packages/base/src/components/ToggleSwitch/ToggleSwitch.types.ts
> +  isDisabled?: boolean;
변경완료!

2023-10-10 06:49 UTC, merged