feature/base/button
shopl/shoplflow pull request #81
Opened 2023-10-04 02:06 UTC by velo-kim

## 🔨작업 내용

- Button, IconButton 컴포넌트 작업

## 📚 레퍼런스 (또는 새로 알게 된 내용) 혹은 궁금한 사항들
- mdx(스토리 Docs) 작성 시, ArgsTable 컴포넌트 사용 시 Props 추론이 안되어(다른 컴포넌트들은 추론이 잘되고 있네요..), Controls 컴포넌트를 사용하여 Props 보여주고 있습니다. Controls 컴포넌트 사용해도 되는 부분이긴 하지만 왜 추론이 안되는 지 궁금하네요..🤔
- Storybook 관련 file 작성 시(mdx, stories.tsx), 기존에 사용하던 규칙이  있을까요? 

## 머지 전 확인해주세요.

> shoplflow는 [트렁크 기반 전략](https://www.notion.so/shoplworks/Gitflow-19b201245a6d4d129731ec2136c62a8e?pvs=4)을 사용하고 있습니다.
>
> 머지 전에 아래 항목들을 확인해주세요.

- [x] 추가되는 기능에 대한 테스트 코드가 작성되었나요?
- [ ] 해당 업데이트로 인해 기존에 작성된 테스트 코드가 실패하지 않나요?
- [x] 머지 전에 빌드가 성공했나요?
- [x] 린트가 적용되어 있나요?

2023-10-04 23:43 UTC, Jason-Jeong-Dev requested changes

2023-10-04 23:43 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Button/Button.types.ts
> +export type ButtonPropsNotStyled = {
component 타입에 leftSource, leftElement와 같이 공통 타입이 있어요
교체해주시면 감사하겠습니다

2023-10-04 23:43 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Button/Button.types.ts
> +export type ButtonSizeVar = 's' | 'm';
타입들은 전부 대문자로 표기했었는데 소문자로 하는게 더 좋을까요?

2023-10-04 23:43 UTC, Jason-Jeong-Dev commented on packages/base/src/components/IconButton/IconButton.styled.ts
> +      return `
return css``로 하는게 더 좋아보여요!

2023-10-04 23:43 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Button/Button.types.ts
타입들은 type assert로 선언했었는데 통일하면 좋을 것 같아요.!

2023-10-04 23:43 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Button/Button.styled.tsx
> +  border: 1px solid
음 스타일, 사이즈 분기가 많아서 각각 스타일에 따라 return 하는 함수를 만드는게 어떠신가요?
예를 들어 getSizeBySizeVar함수는 padding, height, width를 return 하고
getStyleByStyleVar 함수는 background나 border를 설정하는 방식으로요

2023-10-04 23:43 UTC, Jason-Jeong-Dev commented on .hintrc
요거는 어떤 역할이었죠..? 같이 봤던 것 같은데 기억이 안나네요 ㅋㅋㅋㅋ

2023-10-04 23:49 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Button/Button.stories.tsx
> +    buttonType: {
버튼 타입과 styleVar의 차이가 어떤건가요??
스토리북에서 두가지 타입이 모두 노출되는데 styleVar로 통일이 필요해보여요

2023-10-04 23:49 UTC, Jason-Jeong-Dev commented on packages/base/src/components/IconButton/IconButton.styled.ts
> +  width: ${({ sizeVar }) => {
여기도 마찬가지로 각 사이즈 케이스 별로 width, height를 같이 return하는게 유지보수하기 좋을 것 같아요

2023-10-04 23:49 UTC, Jason-Jeong-Dev commented on packages/base/src/components/IconButton/IconButton.styled.ts
> +  cursor: ${({ disabled }) => (disabled ? 'not-allowed' : 'pointer')};
커서와 opacity가 disabled 상태에 따라 분기 되는데 disabled 상태에 따라 각 스타일이 분기되는 방식이 더 좋을 것 같아요

2023-10-04 23:49 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Button/Button.types.ts
+ as const 나 enum으로 타입을 선언하지 않으면 스토리북에서 select가 아닌 텍스트로 타입을 분기하더라구요ㅜㅜ

2023-10-06 00:58 UTC, velo-kim commented on packages/base/src/components/Button/Button.stories.tsx
> +    buttonType: {
styleVar로 통일 했습니다!

2023-10-09 23:36 UTC, Jason-Jeong-Dev requested changes
수고하셨습니다!

2023-10-09 23:36 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Button/Button.mdx
> +디자인 시스템에서 사용하는  버튼 컴포넌트에요.
띄어쓰기 2번 들어가 있어요!

2023-10-09 23:36 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Button/Button.styled.tsx
> +        border: 1px solid ${colorTokens['primary400']};
colorTokens를 사용하실 때 `colorTokens.primary400` 이런 방식으로 사용해주세요!

2023-10-09 23:36 UTC, Jason-Jeong-Dev commented on packages/base/src/components/Button/Button.types.ts
> +export const buttonStyleVar: ButtonStyleVar[] = ['primary', 'secondary', 'solid', 'ghost'];
타입 관련해서는 전부 대문자로 통일하는게 어떨까용

2023-10-09 23:39 UTC, Jason-Jeong-Dev commented on packages/base/src/components/IconButton/IconButton.styled.ts
> +  ${({ styleVar }) => {
스타일 관련해서도 미리 분리되어있으면 좋을 것 같아요

2023-10-09 23:39 UTC, Jason-Jeong-Dev commented on packages/base/src/components/IconButton/IconButton.types.ts
> +export type IconButtonStyleVar = 'solid' | 'ghost';
대문자 관련! 위와 동일합니다!

2023-10-11 04:31 UTC, velo-kim commented on packages/base/src/components/Button/Button.types.ts
> +export const buttonStyleVar: ButtonStyleVar[] = ['primary', 'secondary', 'solid', 'ghost'];
통일했습니다~

2023-10-26 04:53 UTC, Jason-Jeong-Dev approved these changes
수고하셨습니다~!
argTable 추론 안되는 문제는 제가 따로 한번 볼게요

2023-10-26 04:53 UTC, merged